name: "Format"

on:
  push:

jobs: 
  format:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'gradle'
    - name: run format
      run: ./gradlew clean ktlintFormat

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: 41658782+ChanTsune@users.noreply.github.com
        message: "format commit"
        add: "*/*.kt *.kts"
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
